@extends('layouts.app')
@section('content')
<div class="container">
    <table class="table">
        <tbody> 
            <tr>
                <td>
                    id
                </td>
                 <td>
                    {{$issue->id}}
                </td>
            </tr>
            <tr>
                <td>
                    title
                </td>
                 <td>
                    {{$issue->title}}
                </td>
            </tr>
            <tr>
                <td>
                    description
                </td>
                 <td>
                    {{$issue->description}}
                </td>
            </tr>
            <tr>
                <td>
                    status
                </td>
                 <td>
                    {{$issue->status}}
                </td>
            </tr>
            <tr>
                <td>
                    severity
                </td>
                 <td>
                    {{$issue->severity}}
                </td>
            </tr>
        </tbody>
    </table>
</div>

@endsection